#Requires -Version 7.0
<# Print the declared tool/action/effect inventory from a compiled Core contract.
   The assembly must be rebuilt after source changes; this script never installs or edits it. #>
[CmdletBinding()]
param(
    [string]$CoreAssembly = (Join-Path (Split-Path $PSScriptRoot -Parent) 'src/Horizun.Civil3D.Core/bin/Release/net8.0/Horizun.Civil3D.Core.dll'),
    [string]$OutputPath
)
$ErrorActionPreference = 'Stop'
$path = (Resolve-Path -LiteralPath $CoreAssembly).Path
[Reflection.Assembly]::LoadFrom($path) | Out-Null
$tools = @([Horizun.Civil3D.Core.Contract]::All)
$rows = New-Object System.Collections.Generic.List[object]
foreach ($tool in $tools) {
    $schema = $tool.InputSchemaJson | ConvertFrom-Json
    $actionProperty = $schema.properties.PSObject.Properties['action']
    $actions = if ($actionProperty -and $actionProperty.Value.enum) { @($actionProperty.Value.enum) } else { @('(none)') }
    foreach ($action in $actions) {
        $effect = $tool.Effect.ToString()
        if ($tool.ActionEffects -and $tool.ActionEffects.Keys -contains $action) { $effect = $tool.ActionEffects[$action].ToString() }
        $rows.Add([pscustomobject]@{ Tool = $tool.Name; Action = $action; Effect = $effect; Command = $(if ($tool.Command) { $tool.Command } else { '(server)' }) })
    }
}
$lines = New-Object System.Collections.Generic.List[string]
$lines.Add('# Declared capability catalog')
$lines.Add('')
$lines.Add('Generated by `scripts/export-capability-catalog.ps1` from the rebuilt Core assembly. No Civil 3D host was contacted.')
$lines.Add('')
$lines.Add("Contract: ``$([Horizun.Civil3D.Core.Contract]::Hash)``. Tools: $($tools.Count); declared actions: $(@($rows | Where-Object Action -ne '(none)').Count); rows including actionless tools: $($rows.Count).")
$lines.Add('')
$lines.Add('Counts are declarations, not live verification. A row with `(none)` names a tool without an `action` enum. See [capability review](CAPABILITY_REVIEW.md) and [evidence matrix](CIVIL3D.md).')
$lines.Add('')
$lines.Add('| Tool | Action | Effect | Command |')
$lines.Add('|---|---|---|---|')
foreach ($row in $rows) { $lines.Add("| $($row.Tool) | $($row.Action) | $($row.Effect) | $($row.Command) |") }
if ($OutputPath) {
    Set-Content -LiteralPath $OutputPath -Value $lines -Encoding utf8
    Write-Output "Catalog written: $OutputPath ($($tools.Count) tools, $($rows.Count) rows)."
} else {
    $lines
}
